spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/transaction_db
    username: postgres
    password: Soumyajit123#
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
