name: Java CI with Maven and Spring Boot

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: transaction_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Soumyajit123#
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start Spring Boot Application in Background
        run: |
          mvn spring-boot:run "-Dspring-boot.run.profiles=github" &
          echo "Spring Boot app started in background"

      - name: Wait for Application to be Ready
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:8080; do
            echo "Waiting for Spring Boot app to start..."
            sleep 10
          done

      - name: Run tests
        run: mvn test "-Dspring.profiles.active=github"

      - name: Stop Spring Boot Application
        if: always()
        run: |
          curl -X POST http://localhost:8080/actuator/shutdown





