name: Java CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: transaction_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Soumyajit123#
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start Spring Boot application in background
        run: mvn spring-boot:run "-Dspring-boot.run.profiles=github" &
        shell: bash

      - name: Wait for application to start
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:8080; do
            printf '.'
            sleep 5
          done

      - name: Run tests
        run: mvn clean test "-Dspring.profiles.active=github"




